# Nombre de la aplicación
spring.application.name=diamond-analytics-backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/diamond_analytics
spring.datasource.username=postgres
spring.datasource.password=wirt050706
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT (clave secreta - cámbiala por una segura en producción)
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Logging (opcional)
logging.level.org.springframework.security=DEBUG