spring.application.name=moundmetrics

# Base de datos PostgreSQL (ajusta nombre, usuario y contraseña)
spring.datasource.url=jdbc:postgresql://localhost:5432/moundmetrics_db
spring.datasource.username=postgres
spring.datasource.password=wirt050706
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# API MLB Stats
mlb.api.base-url=https://statsapi.mlb.com/api/v1
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.serialization.write-dates-as-timestamps=false

logging.level.com.tumundomlb.moundmetrics.service.GameSyncService=DEBUG